name: Ejecutar búsqueda con Selenium

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        # node-version: '14' # Puedes especificar otra versión si lo deseas

    - name: Instalar dependencias
      run:
        npm install selenium-webdriver chromedriver

    - name: Ejecutar script de Selenium
      run:
        npm start
